#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and listen to port 80

# update packages list
sudo apt update
# install nginx
sudo apt --yes --force-yes install nginx
# start nginx
service nginx start
