#!/usr/bin/env bash
# configures nginx to run and listen to port 80cat -e 1-debugging_made_short | wc -l
ln --symbolic --force /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

